name: APIDOC

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      working-directory: ./backend

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install
        run: yarn install
        working-directory: ${{ env.working-directory }}
      - name: build
        run: yarn api
        working-directory: ${{ env.working-directory }}
      - name: Deploy
        uses: s0/git-publish-subdir-action@master
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: backend/apidoc
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
